# Pre-commit configuration file.
# see https://pre-commit.com for more information
# see https://pre-commit.com/hooks.html for more hooks

repos:
  # Out of the box hooks for pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^runs/
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=2500"]

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff # Lint
        args: [
          "--fix",
          "--line-length=120",
          "--ignore=F401,D400,D401,D415,D100,D101,D102,D103,D104,D105,D107",  # ignore unused imports and first line ended with dots, question marks, etc.
          "--select=D,E,F,UP,B,SIM,I,W291,W292,W293",
          "--per-file-ignores=__init__.py:D104" # ignore missing docstrings in __init__.py files
        ]
      - id: ruff-format # Format
        args: ["--line-length=120"]

exclude: '\.svg$|\.png$|\.html$'
